Repository ckdwlsrh/household-budget-web, pull requests merged in 2025-04, with the labels that each got.

#10 Feat: 거래 내역 조회 시스템 구현
  package-lock.json
  package.json
  src/api/budgetBook/budgetBookService.js
  src/components/budgetItem/BudgetListItem.vue
  src/pages/budgets/BudgetDetailPage.vue
  src/pages/budgets/BudgetListPage.vue
  src/router/index.js
Labels: enhancement

#34 Refactor 필터별 총 금액 합산 리팩토링
  src/api/category/categoryService.js
  src/pages/HomePage.vue
  src/pages/budgets/BudgetDetailPage.vue
  src/pages/budgets/BudgetListPage.vue
  src/stores/budget.js
Labels: enhancement

#36 [Feat] 거래 내역 추가 기능 완료
  db.json
  src/components/modal/AddBudgetDetail.vue
  src/pages/HomePage.vue
  src/pages/budgets/AddBudgetDetailPage.vue
  src/router/index.js
  src/stores/budget.js
  src/stores/categoryStore.js
  src/stores/counter.js
  src/stores/userStore.js
Labels: enhancement, help wanted

#43 [feat] 거래 내역 수정 기능 구현
  db.json
  src/components/modal/AddBudgetDetail.vue
  src/pages/budgets/BudgetDetailPage.vue
  src/pages/budgets/UpdateBudgetDetailPage.vue
  src/router/index.js
Labels: enhancement

#45 feat: 거래 내역 상세 보기 UI 수정
  src/pages/budgets/BudgetDetailPage.vue
Labels: enhancement

#56 feat: 헤더와 네비게이션 UI 수정
  db.json
  index.html
  src/App.vue
  src/components/Layouts/HeaderView.vue
  src/components/Layouts/NavView.vue
Labels: enhancement

#62 Feat 연도 필터 추가
  src/pages/budgets/BudgetListPage.vue
  src/stores/budget.js
Labels: enhancement, refactoring

#64 feat: 거래내역 페이지에서도 플로팅버튼 추가
  src/pages/HomePage.vue
  src/pages/budgets/BudgetListPage.vue
Labels: enhancement

#67 feat: 거래 내역 페이지의 페이지네이션과 필터기능을 수정하였습니다.
  db.json
  src/pages/budgets/BudgetListPage.vue
  src/stores/budget.js
Labels: bug, enhancement

#72 hotfix: 버그 수정 및 로그인 UI 수정
  src/pages/user/LoginPage.vue
Labels: bug

#75 fix: 거래 내역 추가 새로고침 기능 구현, 공지사항 포인터 추가
  db.json
  src/components/modal/AddBudgetDetail.vue
  src/pages/notices/NoticeListPage.vue
Labels: enhancement

#80 Refactor 수입/지출 별 카테고리 필터 변경
  db.json
  src/stores/budget.js
Labels: refactoring
